osx_image: xcode8.2
language: objective-c
script:
  - xcodebuild -project GIGLibrary.xcodeproj -scheme GIGLibrary -sdk iphonesimulator -destination "OS=10.2,platform=iOS Simulator,name=iPhone 6" test
